#!/bin/bash

cd ../client
go mod tidy
make
go build -o build/passage-connect-client .
cp build/passage-connect-client $HOME/../passage-connect-client
#docker build -t passage-connect-client .

#docker create --name passage-connect-client-container passage-connect-client

#docker cp passage-connect-client-container:/goinstall/pam_passage.so build/

#docker stop passage-connect-client-container
#docker container rm passage-connect-client-container

#cp config/pam.d/passage-connect-auth /etc/pam.d/

#cp build/pam_passage.so /usr/lib64/security/